language: node_js
node_js:
  - node
script: yarn test && yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local-dir: build
